- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install HAProxy
  yum:
    name: haproxy
    state: present


- name: Copy haproxy.cfg.j2
  template:
    src: "haproxy.cfg.j2"
    dest: /etc/haproxy/haproxy.cfg

- name: Enable and restart haproxy
  systemd: 
    name: haproxy
    state: started
    enabled: yes
