---
- name: Generating the Data Encryption Config and Key
  hosts: loadbalancer
  vars_files:
   - variable.yaml
  gather_facts: yes
  become: yes
  roles:
  - ca_tls

- name: distribute certs
  hosts: controlplane
  vars_files:
   - variable.yaml
  gather_facts: yes
  become: yes
  roles:
  - distribute
