- name: Create the Kubernetes configuration directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    recurse: yes
  with_items:
  - /etc/kubernetes/config
  - /var/lib/kubernetes

- name: Download and Install the etcd Binaries
  get_url:
    url: "{{ item }}"
  with_items:
  - "{{ kube-apiserver_url }}"
  - "{{ kube-controller-manager_url }}"
  - "{{ kube-scheduler_url }}"
  - "{{ kubectl_url }}"

- name: Make binaries executable
  command: chmod +x kube-apiserver kube-controller-manager kube-scheduler kubectl

- name: Install the Kubernetes binaries
  command: mv kube-apiserver kube-controller-manager kube-scheduler kubectl /usr/local/bin/

- name: Configure the Kubernetes API Server
  copy:
    src: "{{ item }}"
    dest: /var/lib/kubernetes/
  with_items:
  - ca.crt 
  - ca.key 
  - kube-apiserver.crt 
  - kube-apiserver.key
  - service-account.key 
  - service-account.crt
  - etcd-server.key 
  - etcd-server.crt 
  - encryption-config.yaml

- name: Register internal IP in a variable 
  command: hostname -i
  register: INTERNAL_IP

- name: Copy kube-apiserver.service.j2
  template:
    src: "kube-apiserver.service.j2"
    dest: /etc/systemd/system/kube-apiserver.service

- name: Copy the kube-controller-manager kubeconfig into place
  copy:
   src: "{{ kube_configs/kube-controller-manager.kubeconfig }}"
   dest: /var/lib/kubernetes/

- name: Copy kube-controller-manager.service.j2
  template:
    src: "kube-controller-manager.service.j2"
    dest: /etc/systemd/system/kube-controller-manager.service.j2

- name: Copy the kube-scheduler kubeconfig into place
  copy:
    src: "{{ kube_configs/kube-scheduler.kubeconfig }}"
    dest: /var/lib/kubernetes/

- name: Copy kube-scheduler.service.j2
  template:
    src: "kube-scheduler.service.j2"
    dest: /etc/systemd/system/kube-scheduler.service

- name: Just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Start the Controller Services
  systemd: 
    name: "{{ item }}"
    state: started 
  with_items:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler


 









