- name: Create the Kubernetes configuration directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    recurse: yes
  with_items:
  - /etc/kubernetes/config
  - /var/lib/kubernetes

- name: Download and Install the etcd Binaries
  get_url:
    url: "{{ item }}"
  with_items:
  - "{{ kube-apiserver_url }}"
  - "{{ kube-controller-manager_url }}"
  - "{{ kube-scheduler_url }}"
  - "{{ kubectl_url }}"

- name: 

chmod +x kube-apiserver kube-controller-manager kube-scheduler kubectl
- name: Install the Kubernetes binaries
  command: mv kube-apiserver kube-controller-manager kube-scheduler kubectl /usr/local/bin/

- name: Configure the Kubernetes API Server
  copy:
    src: "{{ item }}"
    dest: /var/lib/kubernetes/
  with_items:
  - ca.crt 
  - ca.key 
  - kube-apiserver.crt 
  - kube-apiserver.key
  - service-account.key 
  - service-account.crt
  - etcd-server.key 
  - etcd-server.crt 
  - encryption-config.yaml
  
