- name: Create private key
  import_tasks: key.yaml

- name: Create CSR using the private key
  import_tasks: csr.yaml

- name: Sign certificate
  import_tasks: cert.yaml

- name: Distribute the Certificates
  import_tasks: dist.yaml
